package com.mycompany.mavenproject1;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.EOFException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.OutputStreamWriter;
import java.io.PrintWriter;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import java.io.Serializable;
import java.net.InetAddress;
import java.net.ServerSocket;
import java.net.Socket;
import java.util.List;
import javax.swing.SwingWorker;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


/**
 *
 * @author user
 */
public class NewJFrame extends javax.swing.JFrame {

   
    
    private static double globalResult = 0.0;
    private static double globalUpperLimit = 0.0;
    private static double globalLowerLimit = 0.0;
    private static double globalStep = 0.0;
    private static double globalPart = 0.0;
    
      public double getglobalUpperLimit(){
        return globalUpperLimit;
    }
    
    public void setglobalUpperLimit(double _globalUpperLimit){
        this.globalUpperLimit = _globalUpperLimit;
    }
    
    
    public static void addToGlobalResult(double value) {
        globalResult += value; // Суммируем результаты всех потоков
    }
    
    public double getGlobalResult(){
        return globalResult;
    }
    
    public void setGlobalResultInNull(){
        this.globalResult = 0.0;
    }
    
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        upper_limit = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        step = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        lower_limit = new javax.swing.JTextPane();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(154, 167, 183));

        jPanel1.setBackground(new java.awt.Color(222, 238, 255));

        jPanel2.setBackground(new java.awt.Color(59, 110, 162));

        jTable1.setBackground(new java.awt.Color(210, 232, 255));
        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(59, 110, 162));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "нижняя граница", "верхняя граница", "шаг интегрирования", "результат вычисления"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setToolTipText("");
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        jTable1.setGridColor(new java.awt.Color(20, 52, 74));
        jTable1.setSelectionBackground(new java.awt.Color(156, 172, 189));
        jTable1.setShowGrid(false);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(59, 110, 162));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Нижний предел (а):");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Верхний предел (b):");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Шаг интегрирования (h):");

        jScrollPane4.setViewportView(upper_limit);

        jScrollPane2.setViewportView(step);

        jScrollPane3.setViewportView(lower_limit);

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setText("Добавить");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton2.setText("Вычислить");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton3.setText("Удалить");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton4.setText("Очистить");
        jButton4.setMaximumSize(new java.awt.Dimension(91, 27));
        jButton4.setMinimumSize(new java.awt.Dimension(91, 27));
        jButton4.setPreferredSize(new java.awt.Dimension(91, 27));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton5.setText("Заполнить");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButton1)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel3)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jButton6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton6.setText("загрузить из файла");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton7.setText("сохранить в файл");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Работа с данными в текстовом виде");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Работа с данными в бинарном виде");

        jButton8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton8.setText("загрузить из файла");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton9.setText("сохранить в файл");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel6.setText("Вычисление определенного интеграла функции 1/x");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton6)
                                .addGap(37, 37, 37)
                                .addComponent(jButton7)
                                .addGap(82, 82, 82)
                                .addComponent(jButton8)
                                .addGap(39, 39, 39)
                                .addComponent(jButton9))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(jLabel4)
                                .addGap(174, 174, 174)
                                .addComponent(jLabel5)))))
                .addContainerGap(154, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton7)
                    .addComponent(jButton8)
                    .addComponent(jButton9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    ArrayList<classRecIntegral> arrayRecIntegral = new ArrayList<>();
    
    //"Добавить"
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:        
        String sLowerLimitValue = lower_limit.getText();
        String sUpperLimitValue = upper_limit.getText();
        String sStepValue = step.getText();
        
        if (sLowerLimitValue.isEmpty() || sUpperLimitValue.isEmpty() || sStepValue.isEmpty()){
            JOptionPane.showMessageDialog(this, "Недостаточно данных", "Ошибка", JOptionPane.ERROR_MESSAGE);
            return;
        }    
        
        double dLowerLimitValue = 0.0, dUpperLimitValue = 0.0, dStepValue = 0.0;
        try{
            dLowerLimitValue = Double.parseDouble(lower_limit.getText());
            dUpperLimitValue = Double.parseDouble(upper_limit.getText()); 
            dStepValue = Double.parseDouble(step.getText());
        } catch (NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Некорректные данные", "Ошибка", JOptionPane.ERROR_MESSAGE);
            return;
        }
                 
        
        try {
            //adding parametrs in ArrayList
            classRecIntegral exemplarRecIntegral = new classRecIntegral(dLowerLimitValue, dUpperLimitValue, dStepValue);
            arrayRecIntegral.add(exemplarRecIntegral);
            
            //adding parametrs in table
            DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
            model.addRow(new Object[]{dLowerLimitValue, dUpperLimitValue, dStepValue});
            
        } catch (classRecIntegralException exc){
            JOptionPane.showMessageDialog(this, exc.getMessage(), "Исключение", JOptionPane.ERROR_MESSAGE);
        }    
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    //Удалить
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();
        
        if (selectedRow == -1){
            JOptionPane.showMessageDialog(this, "Выберите строку для удаления", "Ошибка", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        model.removeRow(selectedRow);
        
        //delete from Array
        arrayRecIntegral.remove(selectedRow);
    }//GEN-LAST:event_jButton3ActionPerformed

    //"Вычислить"
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    

    

    SwingWorker<Void, Double> worker = new SwingWorker<Void, Double>() {
        @Override
        protected Void doInBackground() throws Exception {
            try (ServerSocket s = new ServerSocket(PORT)) {
                System.out.println("Started: " + s);
                while (true) {
                    try (Socket socket = s.accept()) {
                        System.out.println("connect: " + socket);
                        BufferedReader in = new BufferedReader(new InputStreamReader(socket.getInputStream()));
                        PrintWriter out = new PrintWriter(new BufferedWriter(new OutputStreamWriter(socket.getOutputStream())), true);

                        
                        int selectedRow = jTable1.getSelectedRow();
                        double dLowerLimitValue = (double) jTable1.getValueAt(selectedRow, 0);
                        double dUpperLimitValue = (double) jTable1.getValueAt(selectedRow, 1);
                        double dStepValue = (double) jTable1.getValueAt(selectedRow, 2);
    
                        
                        
                        out.println(dLowerLimitValue);
                        out.println(dUpperLimitValue);
                        out.println(dStepValue);

                        String str;
                        while ((str = in.readLine()) != null) {
                            System.out.println("from client: " + str);
                            
                            if (str.equals("END")) {
                                double dSum = getGlobalResult();
                                jTable1.setValueAt(dSum, selectedRow, 3);

                                classRecIntegral modifiableObject = arrayRecIntegral.get(selectedRow);
                                modifiableObject.setRezult(dSum);
                                setGlobalResultInNull();
                                break;
                            }   
                            else{
                            addToGlobalResult(Double.parseDouble(str));
                            out.println(str); 
                            }
                        }
                       
                    } catch (Exception e) {
                        System.out.println("ex:" + e.getMessage());
                    }
                }
            }

        }
    };

    worker.execute();

            
//        //создание потоков
//        List<JThread> threads = new ArrayList<>();
//        int numberOfThreads = 2;
//        setGlobalResultInNull();
//
//        double integralPart = (dUpperLimitValue - dLowerLimitValue)/numberOfThreads;
//        double dUpperLimitValueThread = dUpperLimitValue;
//        double dLowerLimitValueThread = dLowerLimitValue;
//
//        // Запускаем таймер перед началом потоков
//        long startTime = System.nanoTime();
//        for (int i = 0; i < numberOfThreads; i++) {
//            dUpperLimitValueThread = dLowerLimitValueThread + integralPart;
//            JThread thread = new JThread("JThread" + (i + 1), dLowerLimitValueThread, dUpperLimitValueThread, dStepValue);
//            dLowerLimitValueThread += integralPart;
//            thread.start();
//            threads.add(thread);
//        }
//
//        for (JThread thread : threads) {
//            try {
//                thread.join();
//            } catch (InterruptedException e) {
//                Thread.currentThread().interrupt(); // Восстановление статуса прерывания
//                JOptionPane.showMessageDialog(this, "Ошибка при ожидании завершения потоков", "Ошибка", javax.swing.JOptionPane.ERROR_MESSAGE);
//            }
//        }
//        long endTime = System.nanoTime();
//        System.out.printf("global (rezult of all thread) %f\n", getGlobalResult());
//        System.out.printf("time of all threads: %.2f\n", (endTime - startTime) / 1_000_000.0);
//
//
//
//        //цикл для вычисления
//        double dLastStep = 0.0, dSum = 0.0;
//        double dIterationCountWhole = (dUpperLimitValue - dLowerLimitValue)/dStepValue;
//        double dIterationCountWithRest = (dUpperLimitValue - dLowerLimitValue)%dStepValue;
//        dIterationCountWhole = dIterationCountWhole - dIterationCountWithRest;
//        dLastStep = dIterationCountWithRest;
//        double dTempA = dLowerLimitValue;
//
//        long startTime1 = System.nanoTime();
//        for (int i = 0; i < dIterationCountWhole; i++){
//            dSum = dSum + dStepValue/2*((1/dTempA) + (1/(dTempA+dStepValue)));
//            dTempA = dTempA + dStepValue;
//        }
//
//        if (dLastStep > 0){
//            dSum = dSum + ((1/dTempA) + (1/(dTempA + dLastStep)))*dLastStep/2;
//        }
//        long endTime1 = System.nanoTime();
//        System.out.printf("time of one thread (main thread): %.2f\n\n", (endTime1 - startTime1) / 1_000_000.0);


        //dSum
        
        
//        //создание потоков
//        List<JThread> threads = new ArrayList<>();
//        int numberOfThreads = 2; 
//        setGlobalResultInNull();
//         
//        double integralPart = (dUpperLimitValue - dLowerLimitValue)/numberOfThreads;
//        double dUpperLimitValueThread = dUpperLimitValue;
//        double dLowerLimitValueThread = dLowerLimitValue;
//        
//        // Запускаем таймер перед началом потоков
//        long startTime = System.nanoTime();
//        for (int i = 0; i < numberOfThreads; i++) {
//            dUpperLimitValueThread = dLowerLimitValueThread + integralPart;
//            JThread thread = new JThread("JThread" + (i + 1), dLowerLimitValueThread, dUpperLimitValueThread, dStepValue);
//            dLowerLimitValueThread += integralPart;
//            thread.start();
//            threads.add(thread);
//        }
//        
//        for (JThread thread : threads) {
//            try {                
//                thread.join();
//            } catch (InterruptedException e) {
//                Thread.currentThread().interrupt(); // Восстановление статуса прерывания
//                JOptionPane.showMessageDialog(this, "Ошибка при ожидании завершения потоков", "Ошибка", javax.swing.JOptionPane.ERROR_MESSAGE);
//            }
//        }
//        long endTime = System.nanoTime();
//        System.out.printf("global (rezult of all thread) %f\n", getGlobalResult());
//        System.out.printf("time of all threads: %.2f\n", (endTime - startTime) / 1_000_000.0);
//         
//        
//        
//        //цикл для вычисления
//        double dLastStep = 0.0, dSum = 0.0;
//        double dIterationCountWhole = (dUpperLimitValue - dLowerLimitValue)/dStepValue;
//        double dIterationCountWithRest = (dUpperLimitValue - dLowerLimitValue)%dStepValue;
//        dIterationCountWhole = dIterationCountWhole - dIterationCountWithRest;
//        dLastStep = dIterationCountWithRest;
//        double dTempA = dLowerLimitValue;
//        
//        long startTime1 = System.nanoTime();
//        for (int i = 0; i < dIterationCountWhole; i++){
//            dSum = dSum + dStepValue/2*((1/dTempA) + (1/(dTempA+dStepValue)));
//            dTempA = dTempA + dStepValue;
//        }
//        
//        if (dLastStep > 0){
//            dSum = dSum + ((1/dTempA) + (1/(dTempA + dLastStep)))*dLastStep/2;
//        }
//        long endTime1 = System.nanoTime();
//        System.out.printf("time of one thread (main thread): %.2f\n\n", (endTime1 - startTime1) / 1_000_000.0);
    }//GEN-LAST:event_jButton2ActionPerformed

    //"Очистить"
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        // DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        // int iRowCount = model.getRowCount();
        // for (int i = iRowCount-1; i >= 0 ; i--){
        //     model.removeRow(i);
        // }
        
        ((DefaultTableModel)jTable1.getModel()).setRowCount(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    //"Заполнить"
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();

        for (classRecIntegral param : arrayRecIntegral) {
            model.addRow(new Object[]{
                param.getLowerLimitValue(), 
                param.getUpperLimitValue(), 
                param.getStepValue(), 
                param.getRezult()
            });
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    //чтение из файла в текстовом виде
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChoose = new JFileChooser("C:\\02_psu\\java_lab\\mavenproject1\\");
        fileChoose.setDialogTitle("Выбор файла для чтения");
        int userSelection = fileChoose.showSaveDialog(null);

        if (userSelection == JFileChooser.APPROVE_OPTION) {
            File fileToSave = fileChoose.getSelectedFile();
            try(FileReader reader = new FileReader(fileToSave))
            {        
                Scanner scan = new Scanner (reader); 
                while (scan.hasNextLine()){
                    String[] line = scan.nextLine().split(" ");

                    //adding parametrs in ArrayList
                    classRecIntegral exemplarRecIntegral = new classRecIntegral(Double.parseDouble(line[0]), Double.parseDouble(line[1]), Double.parseDouble(line[2]));
                    exemplarRecIntegral.setRezult(Double.parseDouble(line[3]));
                    arrayRecIntegral.add(exemplarRecIntegral);

                    //adding parametrs in table
                    DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
                    model.addRow(new Object[]{Double.valueOf(line[0]), Double.valueOf(line[1]), Double.valueOf(line[2]), Double.valueOf(line[3])});
                }
                reader.close();
                JOptionPane.showMessageDialog(this, "Данные успешно загружены из файла в текстовом виде", "Сообщение", JOptionPane.INFORMATION_MESSAGE);
            }
            catch(IOException ex){

                System.out.println(ex.getMessage());
            } catch (classRecIntegralException ex) {
                Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    //запись в файл в текстовом виде
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChoose = new JFileChooser("C:\\02_psu\\java_lab\\mavenproject1\\");
        fileChoose.setDialogTitle("Выбор файла для сохранения"); 
        int userSelection = fileChoose.showSaveDialog(null);

        if (userSelection == JFileChooser.APPROVE_OPTION) {
            File fileToSave = fileChoose.getSelectedFile();
            try(FileWriter writer = new FileWriter(fileToSave, false))
            {
                for (classRecIntegral param : arrayRecIntegral) {
                    String line = String.format("%s %s %s %s", 
                            param.getLowerLimitValue(), param.getUpperLimitValue(), param.getStepValue(), param.getRezult());
                    writer.write(line);
                    writer.append('\n');
                }
                writer.close();
                JOptionPane.showMessageDialog(this, "Данные успешно сохранены в файл в текстовом виде", "Сообщение", JOptionPane.INFORMATION_MESSAGE);
            }
            catch(IOException ex){
                System.out.println(ex.getMessage());
            }
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    //чтение из файла в бинарном виде
    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        
        JFileChooser fileChoose = new JFileChooser("C:\\02_psu\\java_lab\\mavenproject1\\");
        fileChoose.setDialogTitle("Выбор файла для чтения");
        int userSelection = fileChoose.showOpenDialog(null);

        if (userSelection == JFileChooser.APPROVE_OPTION) {
            File fileToRead = fileChoose.getSelectedFile();
            try(ObjectInputStream reader = new ObjectInputStream(new FileInputStream(fileToRead)))
            {   
                while (true) { 
                    try {
                        classRecIntegral exemplarRecIntegral = (classRecIntegral) reader.readObject();
                        
                        //adding parametrs in ArrayList
                        arrayRecIntegral.add(exemplarRecIntegral);

                        //adding parametrs in table
                        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
                        model.addRow(new Object[]{
                            exemplarRecIntegral.getLowerLimitValue(),
                            exemplarRecIntegral.getUpperLimitValue(),
                            exemplarRecIntegral.getStepValue(),
                            exemplarRecIntegral.getRezult()
                        });
                    } catch (EOFException e) {
                        break; // Выход из цикла, когда достигнут конец файла
                    } catch (ClassNotFoundException ex) {
                        Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                JOptionPane.showMessageDialog(this, "Данные успешно загружены из файла в бинарном виде", "Сообщение", JOptionPane.INFORMATION_MESSAGE);
            }
            catch(IOException ex){
                System.out.println(ex.getMessage());
            }
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    //запись в файл в бинарном виде
    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChoose = new JFileChooser("C:\\02_psu\\java_lab\\mavenproject1\\");
        fileChoose.setDialogTitle("Выбор файла для сохранения"); 
        int userSelection = fileChoose.showSaveDialog(null);

        if (userSelection == JFileChooser.APPROVE_OPTION) {
            File fileToSave = fileChoose.getSelectedFile();
            try(ObjectOutputStream writer = new ObjectOutputStream(new FileOutputStream(fileToSave)))
            {
                for (classRecIntegral param : arrayRecIntegral) {                  
                    writer.writeObject(param);
                }
                writer.close();
                JOptionPane.showMessageDialog(this, "Данные успешно сохранены в файл в бинарном виде", "Сообщение", JOptionPane.INFORMATION_MESSAGE);
            }
            catch(IOException ex){
                System.out.println(ex.getMessage());
            }
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     */
    
    
//    private static void handleClient(Socket socket) {
//        try (
//                BufferedReader in = new BufferedReader(new InputStreamReader(socket.getInputStream()));
//                PrintWriter out = new PrintWriter(new BufferedWriter(new OutputStreamWriter(socket.getOutputStream())), true);
//        ) {
//            // Отправка значений
//            double dLowerLimitValue = 1;
//            double dUpperLimitValue = 10.0;
//            double dStepValue = 0.5;
//
//            out.println(dLowerLimitValue);
//            out.println(dUpperLimitValue);
//            out.println(dStepValue);
//
//            String str;
//            while ((str = in.readLine()) != null) {
//                System.out.println("from client: " + str);
//                addToGlobalResult(Double.parseDouble(str));
//                out.println(str); // Отправка обратно измененного значения для клиента
//                // if (str.equals("END")) break;
//            }
//        } catch (Exception e) {
//            System.out.println("401: " + e.getMessage());
//        } finally {
//            try {
//                socket.close(); // Закрыть сокет клиента
//                System.out.println("close");
//            } catch (Exception e) {
//                System.out.println("error close: " + e.getMessage());
//            }
//        }
//    }
    
    // Выбираем порт вне пределов 1-1024:
    public static final int PORT = 8080;
    
    public static void main(String args[]) throws IOException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new NewJFrame().setVisible(true);
        });
        
 
  
        //
    
        
        
//        try {                                                                       // Блокирует до тех пор, пока не возникнет соединение:
//            Socket socket = s.accept();
//            try {
//                System.out.println("Connection accepted: " + socket);
//                BufferedReader in = new BufferedReader(new InputStreamReader(socket.getInputStream()));
//                
//                // Вывод автоматически выталкивается из буфера PrintWriter'ом
//                PrintWriter out = new PrintWriter(new BufferedWriter(
//                new OutputStreamWriter(socket.getOutputStream())), true);
//                
//                 // Отправка значений
//                double dLowerLimitValue = 1;
//                double dUpperLimitValue = 10.0;
//                double dStepValue = 0.5;
//                
//
//                out.println(dLowerLimitValue);
//                out.println(dUpperLimitValue);
//                out.println(dStepValue);
//                
//                while (true) {
//                    String str = in.readLine();
//                    //if (str.equals("END2"))
//                    //break;
//                    System.out.println("From client: " + str);
//                    addToGlobalResult(Double.parseDouble(str));
//                    out.println(str);
//                }
//            }                                                                       // Всегда закрываем два сокета...
//            finally {
//                //System.out.println("closing...");
//                //socket.close();
//                
//            }
//        }
//        finally {
//            s.close();
//       
//        }       
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextPane lower_limit;
    private javax.swing.JTextPane step;
    private javax.swing.JTextPane upper_limit;
    // End of variables declaration//GEN-END:variables
}
